/* Goxel 3D voxels editor
 *
 * copyright (c) 2024
 *
 * Goxel is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.

 * Goxel is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.

 * You should have received a copy of the GNU General Public License along with
 * goxel.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "file_format.h"
#include "goxel.h"
#include <time.h>



typedef struct {
    union {
        struct {
            float    v[3];
            uint8_t  c[3];
        };
        float vn[3];
        struct {
            int  vs[4];
            int vns[4];
        };
    };
} line_t;

static UT_icd line_icd = {sizeof(line_t), NULL, NULL, NULL};

static int lines_find(UT_array *lines, const line_t *line, int search_nb)
{
    int i, len;
    line_t *l;
    len = utarray_len(lines);
    for (i = len - 1; (i >= 0) && (i > len - 1 - search_nb); i--) {
        l = (line_t*)utarray_eltptr(lines, i);
        if (memcmp(l, line, sizeof(*line)) == 0) return i + 1;
    }
    return 0;
}

static int lines_add(UT_array *lines, const line_t *line, int search_nb)
{
    int idx;
    idx = lines_find(lines, line, search_nb);
    if (idx) return idx - 1; // FBX indices are 0-based
    utarray_push_back(lines, line);
    return utarray_len(lines) - 1; // Return 0-based index
}

static void write_fbx_header(FILE *out)
{
    fprintf(out, "; FBX 7.3.0 project file\n");
    fprintf(out, "; Generated by Goxel\n\n");
    fprintf(out, "FBXHeaderExtension:  {\n");
    fprintf(out, "\tFBXHeaderVersion: 1003\n");
    fprintf(out, "\tFBXVersion: 7300\n");
    fprintf(out, "\tCreationTimeStamp:  {\n");
    fprintf(out, "\t\tVersion: 1000\n");
    fprintf(out, "\t\tYear: 2024\n");
    fprintf(out, "\t\tMonth: 1\n");
    fprintf(out, "\t\tDay: 1\n");
    fprintf(out, "\t\tHour: 0\n");
    fprintf(out, "\t\tMinute: 0\n");
    fprintf(out, "\t\tSecond: 0\n");
    fprintf(out, "\t\tMillisecond: 0\n");
    fprintf(out, "\t}\n");
    fprintf(out, "\tCreator: \"Goxel\"\n");
    fprintf(out, "}\n\n");
    fprintf(out, "GlobalSettings:  {\n");
    fprintf(out, "\tVersion: 1000\n");
    fprintf(out, "\tProperties70:  {\n");
    fprintf(out, "\t\tP: \"UpAxis\", \"int\", \"Integer\", \"\",1\n");
    fprintf(out, "\t\tP: \"UpAxisSign\", \"int\", \"Integer\", \"\",1\n");
    fprintf(out, "\t\tP: \"FrontAxis\", \"int\", \"Integer\", \"\",2\n");
    fprintf(out, "\t\tP: \"FrontAxisSign\", \"int\", \"Integer\", \"\",1\n");
    fprintf(out, "\t\tP: \"CoordAxis\", \"int\", \"Integer\", \"\",0\n");
    fprintf(out, "\t\tP: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1\n");
    fprintf(out, "\t\tP: \"OriginalUpAxis\", \"int\", \"Integer\", \"\",1\n");
    fprintf(out, "\t\tP: \"OriginalUpAxisSign\", \"int\", \"Integer\", \"\",1\n");
    fprintf(out, "\t\tP: \"UnitScaleFactor\", \"double\", \"Number\", \"\",100\n");
    fprintf(out, "\t\tP: \"OriginalUnitScaleFactor\", \"double\", \"Number\", \"\",100\n");
    fprintf(out, "\t}\n");
    fprintf(out, "}\n\n");
}

static int export(const volume_t *volume, const char *path)
{
    voxel_vertex_t* verts;
    float v[3];
    uint8_t c[3];
    int nb_elems, i, j, bpos[3];
    float mat[4][4];
    FILE *out;
    const int N = BLOCK_SIZE;
    int size = 0, subdivide;
    UT_array *lines_f, *lines_v, *lines_vn;
    line_t line, face, *line_ptr = NULL;
    volume_iterator_t iter;
    
    // Goxel coordinate system to standard Y-Up
    static const float ZUP2YUP[4][4] = {
        {1, 0, 0, 0}, {0, 0, -1, 0}, {0, 1, 0, 0}, {0, 0, 0, 1},
    };

    utarray_new(lines_f, &line_icd);
    utarray_new(lines_v, &line_icd);
    utarray_new(lines_vn, &line_icd);
    
    verts = calloc(N * N * N * 6 * 4, sizeof(*verts));
    face = (line_t){};
    iter = volume_get_iterator(volume, VOLUME_ITER_TILES | VOLUME_ITER_INCLUDES_NEIGHBORS);
    
    while (volume_iter(&iter, bpos)) {
        mat4_set_identity(mat);
        mat4_mul(ZUP2YUP, mat, mat); // Ensure Y Up
        mat4_itranslate(mat, bpos[0], bpos[1], bpos[2]);
        
        nb_elems = volume_generate_vertices(volume, bpos, goxel.rend.settings.effects, verts, &size, &subdivide);
        
        for (i = 0; i < nb_elems; i++) {
            for (j = 0; j < size; j++) {
                v[0] = verts[i * size + j].pos[0] / (float)subdivide;
                v[1] = verts[i * size + j].pos[1] / (float)subdivide;
                v[2] = verts[i * size + j].pos[2] / (float)subdivide;
                mat4_mul_vec3(mat, v, v);
                memcpy(c, verts[i * size + j].color, 3);
                line = (line_t){.v = {v[0], v[1], v[2]}, .c = {c[0], c[1], c[2]}};
                face.vs[j] = lines_add(lines_v, &line, 1024);
            }
            for (j = 0; j < size; j++) {
                v[0] = verts[i * size + j].normal[0];
                v[1] = verts[i * size + j].normal[1];
                v[2] = verts[i * size + j].normal[2];
                mat4_mul_dir3(mat, v, v);
                line = (line_t){.vn = {v[0], v[1], v[2]}};
                face.vns[j] = lines_add(lines_vn, &line, 512);
            }
            lines_add(lines_f, &face, 0);
        }
    }
    
    out = fopen(path, "w");
    if (!out) {
        free(verts);
        return -1;
    }

    write_fbx_header(out);

    fprintf(out, "Documents:  {\n");
    fprintf(out, "\tCount: 1\n");
    fprintf(out, "\tDocument: 1234567890, \"\", \"Scene\" {\n");
    fprintf(out, "\t\tProperties70:  {\n");
    fprintf(out, "\t\t\tP: \"SourceObject\", \"object\", \"\", \"\"\n");
    fprintf(out, "\t\t\tP: \"ActiveAnimStackName\", \"KString\", \"\", \"\", \"\"\n");
    fprintf(out, "\t\t}\n");
    fprintf(out, "\t\tRootNode: 0\n");
    fprintf(out, "\t}\n");
    fprintf(out, "}\n\n");

    fprintf(out, "Definitions:  {\n");
    fprintf(out, "\tVersion: 100\n");
    fprintf(out, "\tCount: 1\n");
    fprintf(out, "\tObjectType: \"Geometry\" {\n");
    fprintf(out, "\t\tCount: 1\n");
    fprintf(out, "\t}\n");
    fprintf(out, "\tObjectType: \"Model\" {\n");
    fprintf(out, "\t\tCount: 1\n");
    fprintf(out, "\t}\n");
    fprintf(out, "}\n\n");

    fprintf(out, "Objects:  {\n");
    
    // Model Node
    fprintf(out, "\tModel: 2000000000, \"Model::VoxelMesh\", \"Mesh\" {\n");
    fprintf(out, "\t\tVersion: 232\n");
    fprintf(out, "\t\tProperties70:  {\n");
    fprintf(out, "\t\t\tP: \"InheritType\", \"enum\", \"\", \"\",1\n");
    fprintf(out, "\t\t\tP: \"ScalingMax\", \"Vector3D\", \"Vector\", \"\",0,0,0\n");
    fprintf(out, "\t\t\tP: \"DefaultAttributeIndex\", \"int\", \"Integer\", \"\",0\n");
    fprintf(out, "\t\t}\n");
    fprintf(out, "\t\tShading: Y\n");
    fprintf(out, "\t\tCulling: \"CullingOff\"\n");
    fprintf(out, "\t}\n");

    // Geometry Node
    fprintf(out, "\tGeometry: 3000000000, \"Geometry::VoxelMesh\", \"Mesh\" {\n");
    
    // Vertices
    fprintf(out, "\t\tVertices: *%d {\n\t\t\ta: ", utarray_len(lines_v) * 3);
    int cnt = 0;
    while( (line_ptr = (line_t*)utarray_next(lines_v, line_ptr))) {
        fprintf(out, "%s%g,%g,%g", cnt == 0 ? "" : ",", line_ptr->v[0], line_ptr->v[1], line_ptr->v[2]);
        cnt++;
    }
    fprintf(out, "\n\t\t}\n");

    // Face Indices (Negative final index to signify end of face in FBX)
    fprintf(out, "\t\tPolygonVertexIndex: *%d {\n\t\t\ta: ", utarray_len(lines_f) * size);
    cnt = 0;
    while( (line_ptr = (line_t*)utarray_next(lines_f, line_ptr))) {
        for(j=0; j<size; j++) {
            int idx = line_ptr->vs[j];
            if(j == size - 1) idx = (idx * -1) - 1; // FBX End of Polygon
            fprintf(out, "%s%d", cnt == 0 ? "" : ",", idx);
            cnt++;
        }
    }
    fprintf(out, "\n\t\t}\n");

    // Normals (By polygon vertex)
    fprintf(out, "\t\tLayerElementNormal: 0 {\n");
    fprintf(out, "\t\t\tVersion: 101\n");
    fprintf(out, "\t\t\tName: \"\"\n");
    fprintf(out, "\t\t\tMappingInformationType: \"ByPolygonVertex\"\n");
    fprintf(out, "\t\t\tReferenceInformationType: \"Direct\"\n");
    fprintf(out, "\t\t\tNormals: *%d {\n\t\t\t\ta: ", utarray_len(lines_f) * size * 3);
    cnt = 0;
    line_ptr = NULL;
    while( (line_ptr = (line_t*)utarray_next(lines_f, line_ptr))) {
        for(j=0; j<size; j++) {
            line_t *vnl = (line_t*)utarray_eltptr(lines_vn, line_ptr->vns[j]);
            fprintf(out, "%s%g,%g,%g", cnt == 0 ? "" : ",", vnl->vn[0], vnl->vn[1], vnl->vn[2]);
            cnt++;
        }
    }
    fprintf(out, "\n\t\t\t}\n");
    fprintf(out, "\t\t}\n");

    // Colors (By polygon vertex)
    fprintf(out, "\t\tLayerElementColor: 0 {\n");
    fprintf(out, "\t\t\tVersion: 101\n");
    fprintf(out, "\t\t\tName: \"Col\"\n");
    fprintf(out, "\t\t\tMappingInformationType: \"ByPolygonVertex\"\n");
    fprintf(out, "\t\t\tReferenceInformationType: \"Direct\"\n");
    fprintf(out, "\t\t\tColors: *%d {\n\t\t\t\ta: ", utarray_len(lines_f) * size * 4);
    cnt = 0;
    line_ptr = NULL;
    while( (line_ptr = (line_t*)utarray_next(lines_f, line_ptr))) {
        for(j=0; j<size; j++) {
            line_t *vl = (line_t*)utarray_eltptr(lines_v, line_ptr->vs[j]);
            fprintf(out, "%s%f,%f,%f,1.0", cnt == 0 ? "" : ",", vl->c[0]/255.0f, vl->c[1]/255.0f, vl->c[2]/255.0f);
            cnt++;
        }
    }
    fprintf(out, "\n\t\t\t}\n");
    fprintf(out, "\t\t}\n");

    // Layer 0 definitions
    fprintf(out, "\t\tLayer: 0 {\n");
    fprintf(out, "\t\t\tVersion: 100\n");
    fprintf(out, "\t\t\tLayerElement:  {\n");
    fprintf(out, "\t\t\t\tType: \"LayerElementNormal\"\n");
    fprintf(out, "\t\t\t\tTypedIndex: 0\n");
    fprintf(out, "\t\t\t}\n");
    fprintf(out, "\t\t\tLayerElement:  {\n");
    fprintf(out, "\t\t\t\tType: \"LayerElementColor\"\n");
    fprintf(out, "\t\t\t\tTypedIndex: 0\n");
    fprintf(out, "\t\t\t}\n");
    fprintf(out, "\t\t}\n");
    fprintf(out, "\t}\n");

    fprintf(out, "}\n\n");

    fprintf(out, "Connections:  {\n");
    fprintf(out, "\tC: \"OO\",3000000000,2000000000\n"); // Connect Geometry to Model
    fprintf(out, "\tC: \"OO\",2000000000,0\n"); // Connect Model to Root
    fprintf(out, "}\n");

    fclose(out);
    utarray_free(lines_f);
    utarray_free(lines_v);
    utarray_free(lines_vn);
    free(verts);
    return 0;
}

static int fbx_export(const file_format_t *format, const image_t *image, const char *path)
{
    const volume_t *volume = goxel_get_layers_volume(image);
    return export(volume, path);
}

FILE_FORMAT_REGISTER(fbx,
    .name = "fbx",
    .exts = {"*.fbx"},
    .exts_desc = "fbx",
    .export_func = fbx_export,
)
